adapter_name_or_path: /root/autodl-tmp/code/output_tcm_lora
bf16: true
cutoff_len: 1048
dataset: medical_device_quote
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: false
eval_steps: 50
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 2
include_num_input_tokens_seen: true
learning_rate: 0.0002
logging_steps: 10
lora_alpha: 32
lora_dropout: 0.1
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 1000
model_name_or_path: /root/autodl-tmp/code/model/Qwen/Qwen2.5-0.5B-Instruct
num_train_epochs: 20.0
optim: adamw_torch
output_dir: saves/Qwen2.5-0.5B-Instruct/lora/train_2026-06-26-14-48-35
packing: false
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 50
stage: sft
template: qwen
trust_remote_code: true
val_size: 0.1
warmup_steps: 20
